# This is a basic workflow to help you get started with Actions

name: 'hetch'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:   # 触发时机
  push:
    branches: [ master ]  # master有更新
  schedule:
    - cron:  '0 */6 * * *'  # 每6小时运行一次

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Build
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
    - name: Commit and push if changed   # 将README.md更新到仓库
      run: |
        git diff
        git config --global user.email "hetchzhao@aliyun.com"
        git config --global user.name "hetchzhao"
        git add -A
        git commit -m "Updated Readme" || exit 
        git push