name: 'hetchzhao'

on:
  push:
    branches: [ master ]  # master有更新
  schedule:
    - cron:  '0 */6 * * *'  # 每6小时运行一次

jobs:
  stale:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d # Install all dependencies, including development ones
    - name: Build
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run build
    - name: Commit and push if changed   # 更新README.md
      run: |
        git diff
        git config --global user.email "hetchzhao@gmail.com"
        git config --global user.name "hetchzhao"
        git add README.md
        git commit -m "Github Action Auto Updated"
        git push
